server:
  port: 9001
  
spring:
  application:
    name: eureka-server
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone: http://localhost:9001/eureka
    fetch-registry: false
    register-with-eureka: false