server:
  port: 9004
  
spring:
  application:
    name: gateway-server
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
          
zuul: 
  routes:
    auth-server:
      path: /auth/**
      serviceId: auth-server
    order-server:
      path: /order/**
      serviceId: order-server      